# Generated by Django 4.0.4 on 2022-06-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('weight', models.SmallIntegerField()),
                ('breed', models.CharField(choices=[('DM', 'Doberman'), ('CR', 'Corgi'), ('BG', 'Beagle'), ('RW', 'Rottweiler'), ('MX', 'Mixed')], default='MX', max_length=2)),
            ],
        ),
    ]
